---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

gitea_urls:
  api: https://onlyhavecans.works/api/v1/
  download: https://onlyhavecans.works

builds:
  - id: blurs
    builder: rust
    binary: blurs
    flags:
      - --release
      - --bin=blurs
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-apple-darwin
  - id: jumble
    builder: rust
    binary: jumble
    flags:
      - --release
      - --bin=jumble
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-apple-darwin
  - id: line_juggle
    builder: rust
    binary: line_juggle
    flags:
      - --release
      - --bin=line_juggle
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-apple-darwin

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^feat(\(.+\))?!?:'
      order: 0
    - title: Bug fixes
      regexp: '^fix(\(.+\))?!?:'
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  gitea:
    owner: tools
    name: img_trash
